name: Build Resource Pack

on:
  push:
    branches:
      - live-v2
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          mkdir pack
          git archive HEAD | tar -x -C pack

          find pack -name '.*' -delete

          cd pack
          zip -r ../Vulengate-Resource-Pack.zip .

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: live
          name: Live Resource Pack
          prerelease: false
          make_latest: false
          files: Vulengate-Resource-Pack.zip
          fail_on_unmatched_files: true
