name: Build Resource Pack

on:
  push:
    branches:
      - live-v2
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          git archive \
            --format=zip \
            --output=Vulengate-Resource-Pack.zip \
            HEAD

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: live
          name: Live Resource Pack
          prerelease: false
          make_latest: false
          files: Vulengate-Resource-Pack.zip
          fail_on_unmatched_files: true
